### ISSUE TITLE
Running email2git

### ISSUE THREAD

**Issue by rralf** [alexcourouble/email2git#1]
Hi,

I'd like to run email2git on my local machine. Many resources are hard-coded in the python files, and the exact steps to run email2git remain unclear to me. What are the steps in what order to run email2git?

What version of python will I have to use? There are some paths in the code that look like they are neither python2 nor python3, such as the following in emaill2git.py:
`print "========================= ", + len(MATCHED_CID) + ," ========================="`

Thanks
  Ralf

**Comment by alexcourouble** [comment]
Hi Ralf,

Thank you for opening an issue. I've been meaning to clean up the code and improve the readme for a while, and this is a good opportunity to do it.

Are you trying to run Email2git for a project using emails as a collaboration workflow? How many commits does your project have? You may not have to run each step depending on the amount of commits and emails you have.

Best,

Alex

**Comment by rralf** [comment]
Hi Alex,

Yes, I'd like to use it for projects using mailing list for their patches, particularly the Linux kernel, which means that in the big picture I might have tens of thousands of emails/commits.

[We're working on related tools](https://github.com/lfd/PaStA) and we'd like to compare our tool with other approaches, one of them being email2git.

Thanks
  Ralf

**Comment by alexcourouble** [comment]
I'd love to hear more about your related tools and to discuss email2git in more details. 

I'll close this issue for now. Please reach out to me: acourouble@vmware.com

Thanks,

Alex
